site_name: Notas de Aula em Sistemas Distribuídos
site_url: https://paulo-coelho.github.io/ds_notes
site_description: Notas de aula do curso de Sistemas Distribuídos da FACOM/UFU

repo_url: https://github.com/paulo-coelho/ds_notes
edit_uri: ""

extra_javascript:
        - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
        - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        - javascripts/mathjaxhelper.js

extra_css:
        - css/extra.css

theme:
        name: material
        font:
          text: Anonymous Pro
          code: Fira Code
        palette:
           - scheme: default
             accent: orange
             primary: blue
             toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to dark mode
           - scheme: slate
             accent: blue
             primary: orange 
             toggle:
                icon: material/toggle-switch
                name: Switch to light mode
        language: pt
        custom_dir: overrides
        features:
           - search.suggest
           - search.highlight
           - navigation.indexes

markdown_extensions:
        - toc:
            toc_depth: 5
        - attr_list
        - mdx_math
        - admonition
        - footnotes
        - pymdownx.arithmatex:
               generic: true
        - pymdownx.betterem:
               smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg
        - pymdownx.highlight:
             linenums: true
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
              custom_fences:
                   - name: mermaid
                     class: mermaid
                     format: !!python/name:pymdownx.superfences.fence_div_format
        - pymdownx.tasklist:
            custom_checkbox: true
        - pymdownx.tabbed
        - pymdownx.tilde

copyright: "Copyright © 2022 Paulo Coelho"

extra:
  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/...
    - icon: fontawesome/brands/github
      link: https://github.com/paulo-coelho/ds_notes 
      name: These notes on Github
#    - icon: fontawesome/brands/slack
#      link: https://slack.knative.dev
#      name: Slack
  # TODO: Replace with https://github.com/mkdocs/mkdocs/pull/2267 once mkdocs 1.2 is out.
#  version_warning: !!python/object/apply:os.getenv ["VERSION_WARNING"]
#  knative_version: !!python/object/apply:os.getenv ["KNATIVE_VERSION"]
#  branch: !!python/object/apply:os.getenv ["SAMPLES_BRANCH", "mkdocs"]
#  analytics:
#    provider: google
#    property: G-65TK61CS8M
  version:
    provider: mike

plugins:
        - search
#        - bibtex:
#            bib_file: "refs.bib"
#            cite_style: "pandoc"
####        - drawio-exporter:
####                cache_dir: 'drawio-exporter'
####                drawio_executable: null
####                drawio_args:
####                    - --no-sandbox
####                format: svg
####                sources: '*.drawio'
        - drawio-exporter:
            # Diagrams are cached to speed up site generation. The default path is
            # drawio-exporter, relative to the documentation directory.
            cache_dir: 'drawio-exporter'
            # Path to the Draw.io executable:
            #   * drawio on Linux
            #   * draw.io on macOS
            #   * or draw.io.exe on Windows
            # We'll look for it on your system's PATH, then default installation
            # paths. If we can't find it we'll warn you.
            drawio_executable: null
            # Additional Draw.io CLI args
            #   * --embed-svg-images will embed external images in SVGS, if format is "svg".
            drawio_args: [--embed-svg-images]
            # Output format (see draw.io --help | grep format)
            format: svg
            # Embed format
            #   * The default is to embed via the <img> tag.
            #   * Consider <object type="image/svg+xml" data="{img_src}"></object>
            #     to enable interactive elements (like hyperlinks) in SVGs.
            #   * Consider {content} to inline SVGs into documents directly, useful
            #     for styling with CSS, preserving interactivity, and improving
            #     search by indexing diagram text.
            embed_format: '<img alt="{img_alt}" src="{img_src}">'
            # Glob pattern for matching source files
            sources: '*.drawio'

nav:
        #- Início: index.html
        - Prefácio: preface/index.md
        - Introdução: intro/index.md
        - Comunicação:
                - comm/index.md
                - Redes: comm/redes/index.md
                - Internet: comm/internet/index.md
                - Sockets: comm/sockets/index.md
                - Representação: comm/datarep/index.md
                - Middlewares: comm/middleware/index.md
                - RPC: comm/rpc/index.md
                - MOM: comm/mom/index.md
                #TODO? - Multicast: comm/multicast.md
                - Epidêmicos: comm/epidemics/index.md
                - Referências: comm/refs/index.md

        - Arquiteturas: 
                - arch/index.md
                - P2P: arch/p2p/index.md
                - Microsserviços: arch/microservices/index.md

        - Modelos: 
                - models/index.md
                - Tipos: models/models/index.md
#                - Processador: models/processor/index.md

        - Coordenação:
                - Concorrência: coord/concurrency/index.md
                - Coordenação: coord/coord/index.md

        - Tempo: 
                - time/index.md
                - Tempo Físico: time/physical/index.md
                - Tempo Lógico: time/logical/index.md
        
        - Tolerância a Faltas: 
                - fault/index.md
                - Falta/Erros/Falhas: fault/failures/index.md
                - Replicação: fault/replication/index.md
                - Detectores de Falhas: fault/failuredetector/index.md
                - Acordo: fault/agreement/index.md
                - Grupos: fault/reconfiguration/index.md
                - Falhas bizantinas: fault/bizantine/index.md
                - Dependabilidade: fault/dependability/index.md

        - Consistência:
                - consistency/index.md
                - Modelos: consistency/consistency_models/index.md
                - Centrado nos Dados: consistency/data_centric/index.md
                - Centrado no Cliente: consistency/client_centric/index.md
                - Gerenciamento de Réplicas: consistency/replica_management/index.md
                - Checkpointing: consistency/checkpointing/index.md
                - Referências: consistency/references/index.md
#
        - Bancos de Dados: db/disdb/index.md
#        
#        - Sistemas de Arquivos: filesystem/disfs/index.md
#
        - Estudos de Caso: 
                - Introdução: cases/index.md
                - Sockets: cases/sockets/index.md
                - Cassandra: cases/cassandra/index.md
                - Chord: cases/chord/index.md
#                - Pastry: cases/pastry/index.md
#                - Dynamo: cases/dynamo/index.md
                - gRPC: cases/grpc/index.md
                - Mosquitto: cases/mosquitto/index.md
#                - RMI: cases/rmi/index.md
                - Thrift: cases/thrift/index.md
#                - Kafka: cases/kafka/index.md
#                - Swim: cases/swim/index.md
#                - Copycat: cases/copycat/index.md
                - Ratis: cases/ratis/index.md
#                - BFT-Smart: cases/bftsmart/index.md
                - Etcd: cases/etcd/index.md
#                - Zookeeper: cases/zookeeper/index.md
#
#                - Referências: cases/refs/index.md
#
#        - Tecnologias: tech/index.md
#
        - Projeto: projeto/index.md
#        - Seminários: seminar/index.md
